languageCode = "en-us"
title = "Buildstarted's ramblings"
theme = "anubis"
paginate = 3

[params]
   author = "Ben Dornis"
   description = "c# dev that enjoys playing around with random ideas."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "auto"
   readMore = false

   # utteranc.es support
   # utterancesRepo = ""  # mandatory
   # utterancesTheme = "" # optional
   # utterancesIssue = "" # optional
   # utterancesLabel = "" # optional

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 2

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/posts/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
